### ISSUE TITLE
Point main in package.json to build/impromptu-menu.js

### ISSUE THREAD

**Issue by rakannimer** [johanneshilden/impromptu-react-sidemenu#1]
Hey ! 
Thank you for building this component it's great.
I'm using it in a project, however to avoid build/watching my node_modules folder it would be great if your package exported a compiled version of the jsx file in modules by changing your package.json to point to the built library.

Thanks again,
Cheers

**Comment by laserpants** [comment]
This is great. I am still not very good at these modern build tools and stuff (and was even less so when creating this library) so I really appreciate this advice. Possibly there are quite a number of other improvements to be made, in particular I was not sure how to deal with the CSS. The current trend within the React community seems to be to inline all styles, so perhaps that approach would be better. 

In any case, I published this to npm now, as version 0.1.1.

**Comment by rakannimer** [comment]
You can either inline the css with something like [Radium](https://github.com/FormidableLabs/radium) and then build it. Or you can _require_ the sass files in your js file and then build it with webpack. 

Either way will work and give you a good dev workflow IMO. The second way (which I prefer) will be much easier to do without changing much of your code. Just require your sass file from your main module and write a webpack.config.js with a sass-loader that will know how to load and compile your sass into vanilla css :) 

Let me know if I can help with that !
